development:

client_id: 3MVG9OI03ecbG2Vqmy.uyygt8zIc9mM9XrcKQk8gIkgTZ28ml1lrzMgvslQ0Wxm8gtlx3qMLYbTXDX5BaTE2y
client_secret: 766202905834188138

production:

client_id: 3MVG9OI03ecbG2Vqmy.uyygt8zADiTqLYjYI.77_Ntgmox73G6j6Sj1pLih0RyNtdPdMFT7kHI9LTQZ2XrRwc
client_secret: 5677725970294344386